### ISSUE TITLE
Changing the instructions.

### ISSUE THREAD

**Issue by kodyvajjha** [gerby-project/gerby-project.github.io#2]
1. You might want to run `flask run` in the directory `.../gerby-website`, _after_ the databases created in `gerby-website/gerby/tools` are moved to this directory.
2. Somehow, even changing the `configuration.py` doesn't seem to take effect - for example, the content of `gerby.configuration.TAGS` still seems to be `stacks.tags` even after the `configuration.py` is changed. Which makes me wonder if this is hardcoded somewhere?

**Comment by pbelmans** [comment]
The repository https://github.com/gerby-project/hello-world documents a minimal working example, which (semi-)automatically checks the results. So the instructions there should contain all the required soft-linking.

I couldn't reproduce the issue with `gerby.configuration.TAGS`. If this is still a problem, please reopen this issue.
