### ISSUE TITLE
Link to source code repository?

### ISSUE THREAD

**Issue by a3nm** [gerby-project/gerby-project.github.io#3]
Hi,

I was surprised not to see on https://gerby-project.github.io/ a visible link to the Gerby source code, maybe it would make sense to add it?

**Comment by pbelmans** [comment]
Very good point, now there's a prominent link!

**Comment by a3nm** [comment]
Awesome, thanks!


On July 7, 2020 3:22:55 PM GMT+02:00, Pieter Belmans <notifications@github.com> wrote:
>Very good point, now there's a prominent link!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gerby-project/gerby-project.github.io/issues/3#issuecomment-654854974

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
